[build]
  publish = "dist"
  command = "yarn generate"

[[redirects]]
from = "https://blog.viviansarazin.com/"
to = "https://www.viviansarazin.com/blog/"
status = 301

[[redirects]]
from = "https://blog.viviansarazin.com/instapy-creer-bot-instagram/"
to = "https://www.viviansarazin.com/blog/instapy-creer-bot-instagram/"
status = 301

[[redirects]]
from = "https://blog.viviansarazin.com/javascript/"
to = "https://www.viviansarazin.com/blog/javascript/"
status = 301